### PR TITLE
Fix typing issue in-percy.d.ts

### PR DESCRIPTION
**Pull request by jruhland**
fixes:

`TS1046: A 'declare' modifier is required for a top level declaration in a.d.ts file.`

### CODE REVIEW

**Comment by timhaines** [comment]
Thanks @jruhland!

**Comment by jruhland** [comment]
sure thing, can you let me know when you re-publish, right now im using a local workaround in our codebase

**Comment by timhaines** [comment]
@jruhland I've published it now, as v0.1.11.  I'd be curious to hear what you're doing to receive this warning.  Are you linting the in-percy.d.ts file somehow?

**Comment by jruhland** [comment]
we are using `inPercy` in a storybook definition, and it was tossing it on build.  The code was still working since we are running the checker on a separate thread, but the warning was annoying, so i thought id fix it for ya.

**Comment by jruhland** [comment]
i was actually very curious why exactly this is as well, since `node_modules` is ignored.

Appreciate the publish, thanks

**Pull request merged**
